# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_checkout:
      - git fetch --tags
    install:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      - uv venv
      - uv pip install .[docs]
    build:
      html:
        - uv run python scripts/plots/delineate_ridge_areas.py
        - uv run python scripts/plots/create_vector_datasets.py
        - uv run python scripts/plots/calc_ridge_metrics.py
        - .venv/bin/sphinx-apidoc -o docs/api --module-first --no-toc --force
          src/scrollstats
        - uv run python -m sphinx -T -b html -d docs/_build/doctrees -D
          language=en docs $READTHEDOCS_OUTPUT/html
