# Adapted from examples shown in https://autobencoder.com/2020-08-24-conda-actions/

name: ScrollStats Test

on: [push]

jobs:
  miniconda:
    name: ScrollStats Test 
    runs-on: "macos-latest"

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: scroll
          environment-file: environment.yml
          auto-activate-base: false
      - shell: bash -l {0}
        run: |
          curl http://download.osgeo.org/grass/mac/grass-7.8.8-arm64.dmg --output grass-7.8.8-arm64.dmg
          hdiutil attach grass-7.8.8-arm64.dmg
          mv /Volumes/GRASS-GIS-7.8.8/GRASS-7.8.app /Applications/
          pytest test_all.py